<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 9 Voting | Econ5/Poli5D</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::bs4_book,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 9 Voting | Econ5/Poli5D" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/geisel.jpg" />
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::bs4_book,
set in the _output.yml file.</p>" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 9 Voting | Econ5/Poli5D" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::bs4_book,
set in the _output.yml file.</p>" />
  <meta name="twitter:image" content="/images/geisel.jpg" />

<meta name="author" content="David Arnold" />


<meta name="date" content="2026-03-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="automated-pollution-monitoring.html"/>
<link rel="next" href="unconditional-cash-transfers.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="toc-logo"><a href="./"><img src="images/logo.png"></a></li>
<li class="divider"></li>
<li class="part"><span><b>I Excel</b></span></li>
<li class="chapter" data-level="1" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html"><i class="fa fa-check"></i><b>1</b> College Instruction Experiments</a>
<ul>
<li class="chapter" data-level="1.1" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#experiments"><i class="fa fa-check"></i><b>1.1</b> Experiments</a></li>
<li class="chapter" data-level="1.2" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#community-college-data"><i class="fa fa-check"></i><b>1.2</b> Community College Data</a></li>
<li class="chapter" data-level="1.3" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#statistical-functions"><i class="fa fa-check"></i><b>1.3</b> Statistical Functions</a></li>
<li class="chapter" data-level="1.4" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#logical-functions"><i class="fa fa-check"></i><b>1.4</b> Logical Functions</a></li>
<li class="chapter" data-level="1.5" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#summary-statistics"><i class="fa fa-check"></i><b>1.5</b> Summary Statistics</a></li>
<li class="chapter" data-level="1.6" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#S:pivottables"><i class="fa fa-check"></i><b>1.6</b> Pivot Tables</a></li>
<li class="chapter" data-level="1.7" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#balance-tables"><i class="fa fa-check"></i><b>1.7</b> Balance Tables</a></li>
<li class="chapter" data-level="1.8" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#S:impact"><i class="fa fa-check"></i><b>1.8</b> Impact of Financial Incentives</a></li>
<li class="chapter" data-level="1.9" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#S:pivotbasic"><i class="fa fa-check"></i><b>1.9</b> Pivot Charts (Basic)</a></li>
<li class="chapter" data-level="1.10" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#S:pivotadvanced"><i class="fa fa-check"></i><b>1.10</b> Pivot Charts (Advanced)</a></li>
<li class="chapter" data-level="1.11" data-path="college-instruction-experiments.html"><a href="college-instruction-experiments.html#S:Conclusion"><i class="fa fa-check"></i><b>1.11</b> Conclusion</a></li>
</ul></li>
<li class="part"><span><b>II Stata</b></span></li>
<li class="chapter" data-level="2" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html"><i class="fa fa-check"></i><b>2</b> Intergenerational Mobility</a>
<ul>
<li class="chapter" data-level="2.1" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#opportunity-insights"><i class="fa fa-check"></i><b>2.1</b> Opportunity Insights</a></li>
<li class="chapter" data-level="2.2" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#quantiles"><i class="fa fa-check"></i><b>2.2</b> Quantiles</a></li>
<li class="chapter" data-level="2.3" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#mobility-definition"><i class="fa fa-check"></i><b>2.3</b> Mobility Definition</a></li>
<li class="chapter" data-level="2.4" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#stata-gui"><i class="fa fa-check"></i><b>2.4</b> Stata GUI</a></li>
<li class="chapter" data-level="2.5" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#do-files"><i class="fa fa-check"></i><b>2.5</b> Do-files</a></li>
<li class="chapter" data-level="2.6" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#working-directory"><i class="fa fa-check"></i><b>2.6</b> Working Directory</a></li>
<li class="chapter" data-level="2.7" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#describe-and-browse"><i class="fa fa-check"></i><b>2.7</b> Describe and Browse</a></li>
<li class="chapter" data-level="2.8" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#summarize"><i class="fa fa-check"></i><b>2.8</b> Summarize</a></li>
<li class="chapter" data-level="2.9" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#generate"><i class="fa fa-check"></i><b>2.9</b> Generate</a></li>
<li class="chapter" data-level="2.10" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#binary-variables"><i class="fa fa-check"></i><b>2.10</b> Binary Variables</a></li>
<li class="chapter" data-level="2.11" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#if-statements"><i class="fa fa-check"></i><b>2.11</b> If Statements</a></li>
<li class="chapter" data-level="2.12" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#histogram-theoretical"><i class="fa fa-check"></i><b>2.12</b> Histogram (Theoretical)</a></li>
<li class="chapter" data-level="2.13" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#histogram-data"><i class="fa fa-check"></i><b>2.13</b> Histogram (Data)</a></li>
<li class="chapter" data-level="2.14" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#histogram-aesthetics"><i class="fa fa-check"></i><b>2.14</b> Histogram (Aesthetics)</a></li>
<li class="chapter" data-level="2.15" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#conclusion"><i class="fa fa-check"></i><b>2.15</b> Conclusion</a></li>
<li class="chapter" data-level="" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#command-descriptions"><i class="fa fa-check"></i><u>Command Descriptions</u></a></li>
<li class="chapter" data-level="" data-path="intergenerational-mobility.html"><a href="intergenerational-mobility.html#references"><i class="fa fa-check"></i>References</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html"><i class="fa fa-check"></i><b>3</b> Discrimination in Police Stops</a>
<ul>
<li class="chapter" data-level="3.1" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#sopp-intro"><i class="fa fa-check"></i><b>3.1</b> SOPP Intro</a></li>
<li class="chapter" data-level="3.2" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#sopp-data"><i class="fa fa-check"></i><b>3.2</b> SOPP Data</a></li>
<li class="chapter" data-level="3.3" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#veil-of-darkness-vod"><i class="fa fa-check"></i><b>3.3</b> Veil of Darkness (VOD)</a></li>
<li class="chapter" data-level="3.4" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#data-wrangling"><i class="fa fa-check"></i><b>3.4</b> Data Wrangling</a></li>
<li class="chapter" data-level="3.5" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#append"><i class="fa fa-check"></i><b>3.5</b> Append</a></li>
<li class="chapter" data-level="3.6" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#merge-basics"><i class="fa fa-check"></i><b>3.6</b> Merge Basics</a></li>
<li class="chapter" data-level="3.7" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#merge-advanced"><i class="fa fa-check"></i><b>3.7</b> Merge Advanced</a></li>
<li class="chapter" data-level="3.8" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#build-data"><i class="fa fa-check"></i><b>3.8</b> Build Data</a></li>
<li class="chapter" data-level="3.9" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#date-time"><i class="fa fa-check"></i><b>3.9</b> Date-Time</a></li>
<li class="chapter" data-level="3.10" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#implement-vod"><i class="fa fa-check"></i><b>3.10</b> Implement VOD</a></li>
<li class="chapter" data-level="3.11" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#bar-graphs"><i class="fa fa-check"></i><b>3.11</b> Bar Graphs</a></li>
<li class="chapter" data-level="3.12" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#collapse"><i class="fa fa-check"></i><b>3.12</b> Collapse</a></li>
<li class="chapter" data-level="3.13" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#visualizing-veil-of-darkness"><i class="fa fa-check"></i><b>3.13</b> Visualizing Veil of Darkness</a></li>
<li class="chapter" data-level="3.14" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#improving-aesthetics"><i class="fa fa-check"></i><b>3.14</b> Improving Aesthetics</a></li>
<li class="chapter" data-level="3.15" data-path="discrimination-in-police-stops.html"><a href="discrimination-in-police-stops.html#conclusion-1"><i class="fa fa-check"></i><b>3.15</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="classroom-technology.html"><a href="classroom-technology.html"><i class="fa fa-check"></i><b>4</b> Classroom Technology</a>
<ul>
<li class="chapter" data-level="4.1" data-path="classroom-technology.html"><a href="classroom-technology.html#disrupting-education-intro"><i class="fa fa-check"></i><b>4.1</b> Disrupting Education Intro</a></li>
<li class="chapter" data-level="4.2" data-path="classroom-technology.html"><a href="classroom-technology.html#linear-regression-theory"><i class="fa fa-check"></i><b>4.2</b> Linear Regression (Theory)</a></li>
<li class="chapter" data-level="4.3" data-path="classroom-technology.html"><a href="classroom-technology.html#predicted-values"><i class="fa fa-check"></i><b>4.3</b> Predicted Values</a></li>
<li class="chapter" data-level="4.4" data-path="classroom-technology.html"><a href="classroom-technology.html#slope-coefficient"><i class="fa fa-check"></i><b>4.4</b> Slope Coefficient</a></li>
<li class="chapter" data-level="4.5" data-path="classroom-technology.html"><a href="classroom-technology.html#regression-stata"><i class="fa fa-check"></i><b>4.5</b> Regression (Stata)</a></li>
<li class="chapter" data-level="4.6" data-path="classroom-technology.html"><a href="classroom-technology.html#predict"><i class="fa fa-check"></i><b>4.6</b> Predict</a></li>
<li class="chapter" data-level="4.7" data-path="classroom-technology.html"><a href="classroom-technology.html#macros"><i class="fa fa-check"></i><b>4.7</b> Macros</a></li>
<li class="chapter" data-level="4.8" data-path="classroom-technology.html"><a href="classroom-technology.html#explore-data"><i class="fa fa-check"></i><b>4.8</b> Explore Data</a></li>
<li class="chapter" data-level="4.9" data-path="classroom-technology.html"><a href="classroom-technology.html#summary-statistics-1"><i class="fa fa-check"></i><b>4.9</b> Summary Statistics</a></li>
<li class="chapter" data-level="4.10" data-path="classroom-technology.html"><a href="classroom-technology.html#binary-regression"><i class="fa fa-check"></i><b>4.10</b> Binary Regression</a></li>
<li class="chapter" data-level="4.11" data-path="classroom-technology.html"><a href="classroom-technology.html#mindspark-results"><i class="fa fa-check"></i><b>4.11</b> Mindspark Results</a></li>
<li class="chapter" data-level="4.12" data-path="classroom-technology.html"><a href="classroom-technology.html#regression-tables"><i class="fa fa-check"></i><b>4.12</b> Regression Tables</a></li>
<li class="chapter" data-level="4.13" data-path="classroom-technology.html"><a href="classroom-technology.html#conditional-regressions"><i class="fa fa-check"></i><b>4.13</b> Conditional Regressions</a></li>
<li class="chapter" data-level="4.14" data-path="classroom-technology.html"><a href="classroom-technology.html#conclusion-2"><i class="fa fa-check"></i><b>4.14</b> Conclusion</a></li>
<li class="chapter" data-level="" data-path="classroom-technology.html"><a href="classroom-technology.html#command-descriptions-1"><i class="fa fa-check"></i><u>Command Descriptions</u></a></li>
<li class="chapter" data-level="" data-path="classroom-technology.html"><a href="classroom-technology.html#animated-concepts"><i class="fa fa-check"></i><u>Animated Concepts</u></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="legacy-of-colonial-medicine.html"><a href="legacy-of-colonial-medicine.html"><i class="fa fa-check"></i><b>5</b> Legacy of Colonial Medicine</a>
<ul>
<li class="chapter" data-level="5.1" data-path="legacy-of-colonial-medicine.html"><a href="legacy-of-colonial-medicine.html#colonial-medicine-intro"><i class="fa fa-check"></i><b>5.1</b> Colonial Medicine Intro</a></li>
<li class="chapter" data-level="5.2" data-path="legacy-of-colonial-medicine.html"><a href="legacy-of-colonial-medicine.html#value-labels"><i class="fa fa-check"></i><b>5.2</b> Value Labels</a></li>
<li class="chapter" data-level="5.3" data-path="legacy-of-colonial-medicine.html"><a href="legacy-of-colonial-medicine.html#missing-values"><i class="fa fa-check"></i><b>5.3</b> Missing Values</a></li>
<li class="chapter" data-level="5.4" data-path="legacy-of-colonial-medicine.html"><a href="legacy-of-colonial-medicine.html#binned-scatterplots-theory"><i class="fa fa-check"></i><b>5.4</b> Binned Scatterplots (Theory)</a></li>
<li class="chapter" data-level="5.5" data-path="legacy-of-colonial-medicine.html"><a href="legacy-of-colonial-medicine.html#binned-scatterplots-stata"><i class="fa fa-check"></i><b>5.5</b> Binned Scatterplots (Stata)</a></li>
<li class="chapter" data-level="5.6" data-path="legacy-of-colonial-medicine.html"><a href="legacy-of-colonial-medicine.html#conclusion-3"><i class="fa fa-check"></i><b>5.6</b> Conclusion</a></li>
<li class="chapter" data-level="" data-path="legacy-of-colonial-medicine.html"><a href="legacy-of-colonial-medicine.html#command-descriptions-2"><i class="fa fa-check"></i><u>Command Descriptions</u></a></li>
</ul></li>
<li class="part"><span><b>III R</b></span></li>
<li class="chapter" data-level="6" data-path="resume-experiments.html"><a href="resume-experiments.html"><i class="fa fa-check"></i><b>6</b> Resume Experiments</a>
<ul>
<li class="chapter" data-level="6.1" data-path="resume-experiments.html"><a href="resume-experiments.html#correspondence-studies"><i class="fa fa-check"></i><b>6.1</b> Correspondence Studies</a></li>
<li class="chapter" data-level="6.2" data-path="resume-experiments.html"><a href="resume-experiments.html#installing-rrstudio"><i class="fa fa-check"></i><b>6.2</b> Installing R/RStudio</a></li>
<li class="chapter" data-level="6.3" data-path="resume-experiments.html"><a href="resume-experiments.html#rstudio-interface"><i class="fa fa-check"></i><b>6.3</b> RStudio Interface</a></li>
<li class="chapter" data-level="6.4" data-path="resume-experiments.html"><a href="resume-experiments.html#objects"><i class="fa fa-check"></i><b>6.4</b> Objects</a></li>
<li class="chapter" data-level="6.5" data-path="resume-experiments.html"><a href="resume-experiments.html#working-directory-1"><i class="fa fa-check"></i><b>6.5</b> Working Directory</a></li>
<li class="chapter" data-level="6.6" data-path="resume-experiments.html"><a href="resume-experiments.html#dataframes"><i class="fa fa-check"></i><b>6.6</b> Dataframes</a></li>
<li class="chapter" data-level="6.7" data-path="resume-experiments.html"><a href="resume-experiments.html#logic"><i class="fa fa-check"></i><b>6.7</b> Logic</a></li>
<li class="chapter" data-level="6.8" data-path="resume-experiments.html"><a href="resume-experiments.html#subsetting-vectors"><i class="fa fa-check"></i><b>6.8</b> Subsetting Vectors</a></li>
<li class="chapter" data-level="6.9" data-path="resume-experiments.html"><a href="resume-experiments.html#subsetting-data-frames"><i class="fa fa-check"></i><b>6.9</b> Subsetting Data Frames</a></li>
<li class="chapter" data-level="6.10" data-path="resume-experiments.html"><a href="resume-experiments.html#conclusion-4"><i class="fa fa-check"></i><b>6.10</b> Conclusion</a></li>
<li class="chapter" data-level="" data-path="resume-experiments.html"><a href="resume-experiments.html#function-descriptions"><i class="fa fa-check"></i><u>Function Descriptions</u></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html"><i class="fa fa-check"></i><b>7</b> The Rug Rat Race</a>
<ul>
<li class="chapter" data-level="7.1" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#time-diaries"><i class="fa fa-check"></i><b>7.1</b> Time Diaries</a></li>
<li class="chapter" data-level="7.2" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#conditional-statements"><i class="fa fa-check"></i><b>7.2</b> Conditional Statements</a></li>
<li class="chapter" data-level="7.3" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#for-loops"><i class="fa fa-check"></i><b>7.3</b> For Loops</a></li>
<li class="chapter" data-level="7.4" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#for-loops-data"><i class="fa fa-check"></i><b>7.4</b> For Loops (Data)</a></li>
<li class="chapter" data-level="7.5" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#tidyverse"><i class="fa fa-check"></i><b>7.5</b> Tidyverse</a></li>
<li class="chapter" data-level="7.6" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#the-pipe-operator"><i class="fa fa-check"></i><b>7.6</b> The Pipe Operator</a></li>
<li class="chapter" data-level="7.7" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#mutate"><i class="fa fa-check"></i><b>7.7</b> Mutate</a></li>
<li class="chapter" data-level="7.8" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#group-by-and-summarize"><i class="fa fa-check"></i><b>7.8</b> Group By and Summarize</a></li>
<li class="chapter" data-level="7.9" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#conclusion-5"><i class="fa fa-check"></i><b>7.9</b> Conclusion</a></li>
<li class="chapter" data-level="" data-path="the-rug-rat-race.html"><a href="the-rug-rat-race.html#function-descriptions-1"><i class="fa fa-check"></i><u>Function Descriptions</u></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html"><i class="fa fa-check"></i><b>8</b> Automated Pollution Monitoring</a>
<ul>
<li class="chapter" data-level="8.1" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#principal-agent-problem"><i class="fa fa-check"></i><b>8.1</b> Principal Agent Problem</a></li>
<li class="chapter" data-level="8.2" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#creating-histograms"><i class="fa fa-check"></i><b>8.2</b> Creating Histograms</a></li>
<li class="chapter" data-level="8.3" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#comparing-histograms"><i class="fa fa-check"></i><b>8.3</b> Comparing Histograms</a></li>
<li class="chapter" data-level="8.4" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#boxplots"><i class="fa fa-check"></i><b>8.4</b> Boxplots</a></li>
<li class="chapter" data-level="8.5" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#scatterplots"><i class="fa fa-check"></i><b>8.5</b> Scatterplots</a></li>
<li class="chapter" data-level="8.6" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#dates"><i class="fa fa-check"></i><b>8.6</b> Dates</a></li>
<li class="chapter" data-level="8.7" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#ggplot2"><i class="fa fa-check"></i><b>8.7</b> ggplot2</a></li>
<li class="chapter" data-level="8.8" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#bar-plots"><i class="fa fa-check"></i><b>8.8</b> Bar Plots</a></li>
<li class="chapter" data-level="8.9" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#conclusion-6"><i class="fa fa-check"></i><b>8.9</b> Conclusion</a></li>
<li class="chapter" data-level="" data-path="automated-pollution-monitoring.html"><a href="automated-pollution-monitoring.html#function-descriptions-2"><i class="fa fa-check"></i><u>Function Descriptions</u></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="voting.html"><a href="voting.html"><i class="fa fa-check"></i><b>9</b> Voting</a>
<ul>
<li class="chapter" data-level="9.1" data-path="voting.html"><a href="voting.html#u.s.-presidential-election"><i class="fa fa-check"></i><b>9.1</b> 2000 U.S. Presidential Election</a></li>
<li class="chapter" data-level="9.2" data-path="voting.html"><a href="voting.html#linear-regression"><i class="fa fa-check"></i><b>9.2</b> Linear Regression</a></li>
<li class="chapter" data-level="9.3" data-path="voting.html"><a href="voting.html#plotting-regression-lines"><i class="fa fa-check"></i><b>9.3</b> Plotting Regression Lines</a></li>
<li class="chapter" data-level="9.4" data-path="voting.html"><a href="voting.html#predicted-values-and-residuals"><i class="fa fa-check"></i><b>9.4</b> Predicted Values and Residuals</a></li>
<li class="chapter" data-level="9.5" data-path="voting.html"><a href="voting.html#get-out-to-vote-experiments"><i class="fa fa-check"></i><b>9.5</b> Get Out to Vote Experiments</a></li>
<li class="chapter" data-level="9.6" data-path="voting.html"><a href="voting.html#regression-binary-variables"><i class="fa fa-check"></i><b>9.6</b> Regression (Binary Variables)</a></li>
<li class="chapter" data-level="9.7" data-path="voting.html"><a href="voting.html#conclusion-7"><i class="fa fa-check"></i><b>9.7</b> Conclusion</a></li>
<li class="chapter" data-level="" data-path="voting.html"><a href="voting.html#function-descriptions-3"><i class="fa fa-check"></i><u>Function Descriptions</u></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="unconditional-cash-transfers.html"><a href="unconditional-cash-transfers.html"><i class="fa fa-check"></i><b>10</b> Unconditional Cash Transfers</a>
<ul>
<li class="chapter" data-level="10.1" data-path="unconditional-cash-transfers.html"><a href="unconditional-cash-transfers.html#motivation"><i class="fa fa-check"></i><b>10.1</b> Motivation</a></li>
<li class="chapter" data-level="10.2" data-path="unconditional-cash-transfers.html"><a href="unconditional-cash-transfers.html#the-data"><i class="fa fa-check"></i><b>10.2</b> The Data</a></li>
<li class="chapter" data-level="10.3" data-path="unconditional-cash-transfers.html"><a href="unconditional-cash-transfers.html#functions-part-1"><i class="fa fa-check"></i><b>10.3</b> Functions (Part 1)</a></li>
<li class="chapter" data-level="10.4" data-path="unconditional-cash-transfers.html"><a href="unconditional-cash-transfers.html#functions-part-2"><i class="fa fa-check"></i><b>10.4</b> Functions (Part 2)</a></li>
<li class="chapter" data-level="10.5" data-path="unconditional-cash-transfers.html"><a href="unconditional-cash-transfers.html#conclusion-8"><i class="fa fa-check"></i><b>10.5</b> Conclusion</a></li>
<li class="chapter" data-level="" data-path="unconditional-cash-transfers.html"><a href="unconditional-cash-transfers.html#function-descriptions-4"><i class="fa fa-check"></i><u>Function Descriptions</u></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Econ5/Poli5D</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="voting" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">Chapter 9</span> Voting<a href="voting.html#voting" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<html>
<head>
<style>
code {
  background-color: #f1f1f1;
}
</style>
</head>
<body>
<div id="u.s.-presidential-election" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> 2000 U.S. Presidential Election<a href="voting.html#u.s.-presidential-election" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this chapter, we will discuss two different voting applications. The first empirical application will study the 2000 U.S. Presidential Election. This election was extremely close. In the end, George W. Bush won the election with 271 electoral votes against Al Gore’s 266.</p>
<p>In the state of Florida, the election was particularly close. In the end, Bush won Florida by just 537 votes, and thus secured Florida’s 25 electoral votes and the election. However, in Florida, there was one county’s results that became particularly controversial: Palm Beach County. Many voters in this county complained about a confusing ballot. They claimed that the layout made it so that they accidentally voted for Pat Buchanan (the Reform Party Candidate) rather than Al Gore.</p>
<p>Figure <a href="voting.html#fig:butterfly">9.1</a> shows the Ballot that was used in Palm Beach County:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:butterfly"></span>
<img src="images/09_palmballot.png" alt="The Butterfly Ballot" width="90%" />
<p class="caption">
Figure 9.1: The Butterfly Ballot
</p>
</div>
<p>In the top left, you can see the first listed candidates are George W. Bush and Dick Cheney (the Republican Candidates). The next candidates (on the right) are actually Pat Buchanan and Ezola Foster (the Reform Party Candidates). However, if you are filling this in quickly, you can see how someone might accidentally think the second selection corresponds to Al Gore and Joe Lieberman.</p>
<p>If enough people made this mistake, this could actually have consequences for who wins the election. Remember, only 537 votes separated George W. Bush and Al Gore. To understand the scope of the problem, we are going to replicate analysis from Wand et al. (2001)<span class="citation">,<a href="#fn12" class="footnote-ref" id="fnref12"><sup>12</sup></a></span> with much of the data and code coming from Kosuke Imai’s Textbook: Quantitative Social Science: An Introduction.<span class="citation">.<a href="#fn13" class="footnote-ref" id="fnref13"><sup>13</sup></a></span></p>
<p>Specifically, if voters are confused by the ballot, we would expect an unusually high number of votes for the Reform party candidates in Palm Beach. But how do we define “an unusually high number of votes”. To operationalize this idea we will use the number of votes in a county for the Reform party in 1996 (the prior election) to predict how many votes a county will cast for the Reform party in 2000. If Palm Beach County has many more votes than predicted, then maybe the Butterfly ballot is the reason why.</p>
<p>To begin exploring this question, let’s load up our data.</p>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="voting.html#cb427-1" tabindex="-1"></a>florida <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;florida.csv&quot;</span>)</span>
<span id="cb427-2"><a href="voting.html#cb427-2" tabindex="-1"></a><span class="co">#&gt; Rows: 67 Columns: 7</span></span>
<span id="cb427-3"><a href="voting.html#cb427-3" tabindex="-1"></a><span class="co">#&gt; ── Column specification ────────────────────────────────────</span></span>
<span id="cb427-4"><a href="voting.html#cb427-4" tabindex="-1"></a><span class="co">#&gt; Delimiter: &quot;,&quot;</span></span>
<span id="cb427-5"><a href="voting.html#cb427-5" tabindex="-1"></a><span class="co">#&gt; chr (1): county</span></span>
<span id="cb427-6"><a href="voting.html#cb427-6" tabindex="-1"></a><span class="co">#&gt; dbl (6): Clinton96, Dole96, Perot96, Bush00, Gore00, Buc...</span></span>
<span id="cb427-7"><a href="voting.html#cb427-7" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb427-8"><a href="voting.html#cb427-8" tabindex="-1"></a><span class="co">#&gt; ℹ Use `spec()` to retrieve the full column specification for this data.</span></span>
<span id="cb427-9"><a href="voting.html#cb427-9" tabindex="-1"></a><span class="co">#&gt; ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</span></span>
<span id="cb427-10"><a href="voting.html#cb427-10" tabindex="-1"></a><span class="fu">head</span>(florida)</span>
<span id="cb427-11"><a href="voting.html#cb427-11" tabindex="-1"></a><span class="co">#&gt; # A tibble: 6 × 7</span></span>
<span id="cb427-12"><a href="voting.html#cb427-12" tabindex="-1"></a><span class="co">#&gt;   county   Clinton96 Dole96 Perot96 Bush00 Gore00 Buchanan00</span></span>
<span id="cb427-13"><a href="voting.html#cb427-13" tabindex="-1"></a><span class="co">#&gt;   &lt;chr&gt;        &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;      &lt;dbl&gt;</span></span>
<span id="cb427-14"><a href="voting.html#cb427-14" tabindex="-1"></a><span class="co">#&gt; 1 Alachua      40144  25303    8072  34124  47365        263</span></span>
<span id="cb427-15"><a href="voting.html#cb427-15" tabindex="-1"></a><span class="co">#&gt; 2 Baker         2273   3684     667   5610   2392         73</span></span>
<span id="cb427-16"><a href="voting.html#cb427-16" tabindex="-1"></a><span class="co">#&gt; 3 Bay          17020  28290    5922  38637  18850        248</span></span>
<span id="cb427-17"><a href="voting.html#cb427-17" tabindex="-1"></a><span class="co">#&gt; 4 Bradford      3356   4038     819   5414   3075         65</span></span>
<span id="cb427-18"><a href="voting.html#cb427-18" tabindex="-1"></a><span class="co">#&gt; 5 Brevard      80416  87980   25249 115185  97318        570</span></span>
<span id="cb427-19"><a href="voting.html#cb427-19" tabindex="-1"></a><span class="co">#&gt; 6 Broward     320736 142834   38964 177323 386561        788</span></span></code></pre></div>
<p>Each row of the data is a county in Florida. In each row, we have counts for different presidential candidates in both 1996 and 2000. For example, in 1996, 40,144 votes were cast in Alachua county for Bill Clinton. 25,303 were cast for Bob Dole.</p>
<p>Our eventual goal will be to use the votes cast for Ross Perot (the Reform Party Candidate) in 1996, to predict how many votes a county will cast for Pat Buchanan in 2000 (the Reform Party Candidate).</p>
<p>The logic behind this design is that we might think counties are relatively consistent in their voting patterns. Maybe Palm Beach County is a county that happens to heavily support the Reform Party Candidates. If this is true, we should see high number of votes for Reform Party Candidates in both 1996 and 2000.</p>
<p>To begin our exploration, let’s visualize the relationship between voting for Ross Perot in 1996 and Pat Buchanan in 2000. To do so we will construct a scatter plot with <code>Perot96</code> on the horizontal axis and <code>Buchanan00</code> on the vertical axis.</p>
<div class="sourceCode" id="cb428"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb428-1"><a href="voting.html#cb428-1" tabindex="-1"></a><span class="fu">ggplot</span>(florida, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>Perot96, <span class="at">y=</span>Buchanan00)) <span class="sc">+</span> </span>
<span id="cb428-2"><a href="voting.html#cb428-2" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:butter1"></span>
<img src="09-week9_files/figure-html/butter1-1.png" alt="Relationship Between Buchanan and Perot Votes" width="80%" />
<p class="caption">
Figure 9.2: Relationship Between Buchanan and Perot Votes
</p>
</div>
<p>We can see there is one point in the top right of this graph that seems to be a bit of an outlier. This county has much higher number of votes for Buchanan than any other county. In order to see which county this is, let’s add the option <code>label=county</code> inside <code>aes()</code>. This will label each marker with the county it represents. To adjust the location and size of the marker, we will also specify <code>geom_text(vjust=1.5,size=3)</code>.</p>
<div class="sourceCode" id="cb429"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb429-1"><a href="voting.html#cb429-1" tabindex="-1"></a><span class="fu">ggplot</span>(florida, </span>
<span id="cb429-2"><a href="voting.html#cb429-2" tabindex="-1"></a>       <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>Perot96, <span class="at">y=</span>Buchanan00, <span class="at">label=</span>county)) <span class="sc">+</span> </span>
<span id="cb429-3"><a href="voting.html#cb429-3" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb429-4"><a href="voting.html#cb429-4" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">vjust=</span><span class="fl">1.5</span>, <span class="at">size=</span><span class="dv">3</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:butter2"></span>
<img src="09-week9_files/figure-html/butter2-1.png" alt="Relationship Between Buchanan and Perot Votes" width="80%" />
<p class="caption">
Figure 9.3: Relationship Between Buchanan and Perot Votes
</p>
</div>
<p>We chose <code>(vjust=1.5,size=3)</code> to make the labels easily readable. You can play around with these parameters to see how it changes the appearance of the figure.</p>
<p>Now with the markers labeled we can see that Palm Beach is indeed the outlier county. But an important next question is how big of an outlier is Palm Beach? Is this enough to potentially change the outcome of the election? To answer this question concretely, we will first learn how to estimate a linear regression in R.</p>
</div>
<div id="linear-regression" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Linear Regression<a href="voting.html#linear-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this section we are going to review linear regression, and then estimate a linear regression which will help us understand whether the butterfly ballot impacted the 2000 U.S. Presidential Election. If you would like a more thorough review of linear regression, look back to Chapter 4 which includes a longer introduction to linear regression.</p>
<p>To review briefly, we can write a general linear regression equation as:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 \cdot X_i + \varepsilon_i
\]</span></p>
<p>Where <span class="math inline">\(Y_i\)</span> is our dependent variable of interest, <span class="math inline">\(X_i\)</span> is our independent variable of interest, <span class="math inline">\(\beta_0\)</span> is the intercept, <span class="math inline">\(\beta_1\)</span> is the slope coefficient and <span class="math inline">\(\varepsilon_i\)</span> is the error term.</p>
<p>In our data, we choose estimates of <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>, which we denote, <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span>, that minimize the sum of squared errors <span class="math inline">\(\sum_{i=1}^N(Y_i-\hat{Y}_i)^2\)</span>.</p>
<p>What do <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> tell us? Let’s talk about <span class="math inline">\(\hat{\beta}_1\)</span> first. This tells us how changes in <span class="math inline">\(X\)</span> are associated with changes in <span class="math inline">\(Y\)</span>. If this value is positive, then increases in <span class="math inline">\(X\)</span> are associated with increases in <span class="math inline">\(Y\)</span>. If it is negative, then increases in <span class="math inline">\(X\)</span> are associated with decreases in <span class="math inline">\(Y\)</span>. The interpretation of <span class="math inline">\(\hat{\beta}_1\)</span> is a 1-unit change in <span class="math inline">\(X\)</span> is associated with a <span class="math inline">\(\hat{\beta}_1\)</span>-unit change in <span class="math inline">\(Y\)</span>.</p>
<p>Once we have our estimates of the intercept and slope, we can also use them to form predictions. For example, the predicted value of <span class="math inline">\(Y\)</span> for an individual with observable <span class="math inline">\(X_i=5\)</span> is equal to:</p>
<p><span class="math display">\[
\hat{Y}_i = \hat{\beta}_0 + \hat{\beta}_1 \cdot 5
\]</span>
This is a good place to re-introduce our empirical application. Our goal is to use the number of votes for Perot in 1996 to predict the number of votes for Buchanan in 2000. One way to do this is to estimate a linear regression of the following form:</p>
<p><span class="math display">\[
Buchanan00_i = \beta_0 + \beta_1 \cdot Perot96_i + \varepsilon_i
\]</span></p>
<p>Once we estimate this regression equation, we can use the estimates to predict the number of Buchanan votes in Palm Beach County and compare to the actual number of votes in Palm Beach County. For example, hypothetically, if we predict Buchanan would receive 1000 votes in Palm Beach, but actually received 2000, then there would be 1000 more votes in Palm Beach than expected.</p>
<p>In R, the function we use to estimate linear regressions is the <code>lm()</code> function. The basic syntax of the command is:</p>
<div class="sourceCode" id="cb430"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb430-1"><a href="voting.html#cb430-1" tabindex="-1"></a>lm.fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(yvar <span class="sc">~</span> xvar, <span class="at">data=</span>df)</span></code></pre></div>
<ul>
<li><p><code>lm.fit</code> stores the estimates of the linear regression as an object in R.</p></li>
<li><p><code>yvar</code> should be replaced with your <strong>dependent variable</strong></p></li>
<li><p><code>xvar</code> should be replaced with your <strong>independent variable</strong></p></li>
<li><p><code>df</code> should be the dataframe that is in your environment.</p></li>
</ul>
<p>In our empirical application, the code below estimates a linear regression with <code>Buchanan00</code> as the dependent variable and <code>Perot96</code> as the independent variable:</p>
<div class="sourceCode" id="cb431"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb431-1"><a href="voting.html#cb431-1" tabindex="-1"></a>lm.florida <span class="ot">&lt;-</span> <span class="fu">lm</span>(Buchanan00 <span class="sc">~</span> Perot96, <span class="at">data=</span>florida)</span></code></pre></div>
<p>To view the basic estimates of the regression, we can type:</p>
<div class="sourceCode" id="cb432"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb432-1"><a href="voting.html#cb432-1" tabindex="-1"></a>lm.florida</span>
<span id="cb432-2"><a href="voting.html#cb432-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb432-3"><a href="voting.html#cb432-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb432-4"><a href="voting.html#cb432-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = Buchanan00 ~ Perot96, data = florida)</span></span>
<span id="cb432-5"><a href="voting.html#cb432-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb432-6"><a href="voting.html#cb432-6" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb432-7"><a href="voting.html#cb432-7" tabindex="-1"></a><span class="co">#&gt; (Intercept)      Perot96  </span></span>
<span id="cb432-8"><a href="voting.html#cb432-8" tabindex="-1"></a><span class="co">#&gt;     1.34575      0.03592</span></span></code></pre></div>
<p>So this displays our estimate of the intercept (<span class="math inline">\(\hat{\beta}_0=1.346\)</span>) and slope coefficient (<span class="math inline">\(\hat{\beta}_1=0.036\)</span>). The intercept tells us where the best fitted line intersects the vertical axis at <span class="math inline">\(X=0\)</span>. In terms of our example, the best fitted line is equal to 1.346 at <span class="math inline">\(Perot96_i=0\)</span>. Another way to interpret this is, hypothetically, if we had a county that cast zero votes for Perot in 1996, we would expect this county to cast 1.346 votes for Buchanan in 2000.</p>
<p>Now onto interpreting <span class="math inline">\(\hat{\beta}_1\)</span>: one additional vote for Perot in 1996 is associated with 0.035 more votes for Buchanan in 2000. You might be a little confused at the moment about why the slope coefficient seems so small. In the next section, we will discuss further how to interpret this regression, and in particular, how we can visualize its results. This will help us understand what our regression results imply in terms of figuring out whether something unusual is occurring in Palm Beach county.</p>
</div>
<div id="plotting-regression-lines" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Plotting Regression Lines<a href="voting.html#plotting-regression-lines" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In the prior section, we estimated</p>
<p><span class="math display">\[
Buchanan00_i = \beta_0 + \beta_1 \cdot Perot96_i + \varepsilon_i
\]</span>
And found <span class="math inline">\(\hat{\beta}_0=1.346\)</span> and <span class="math inline">\(\hat{\beta}_1=0.036\)</span>. These coefficients tells us the intercept and slope of the line that best fits our data. In this section we will show how to plot this best fit line in both base R and ggplot.</p>
<p>To begin, let’s create a scatter plot with <code>Buchanan00</code> on the vertical axis and <code>Perot96</code> on the horizontal axis. We are also going to specify <code>pch=16</code> in this code to change the style of the markers. <code>pch</code> stands for plot character in R and can be used to change the shape or appearance of the points in a scatterplot.</p>
<div class="sourceCode" id="cb433"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb433-1"><a href="voting.html#cb433-1" tabindex="-1"></a><span class="fu">plot</span>(florida<span class="sc">$</span>Perot96, florida<span class="sc">$</span>Buchanan00, </span>
<span id="cb433-2"><a href="voting.html#cb433-2" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">16</span>,</span>
<span id="cb433-3"><a href="voting.html#cb433-3" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Votes for Perot in 1996&quot;</span>, </span>
<span id="cb433-4"><a href="voting.html#cb433-4" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Votes for Buchanan in 2000&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:basescatter1"></span>
<img src="09-week9_files/figure-html/basescatter1-1.png" alt="Relationship Between Buchanan and Perot Votes" width="80%" />
<p class="caption">
Figure 9.4: Relationship Between Buchanan and Perot Votes
</p>
</div>
<p>Now our goal is to add the linear regression line to this plot. To do so, we will use the <code>abline()</code> function. <code>abline()</code> can be used to add lines to plots. If you pass the outcome of a linear regression to <code>abline()</code>, then the fitted line from that regression will be added to the plot. In other words, if we add <code>abline(lm.florida)</code>, then the best-fitted line from this regression will be added to the plot:</p>
<div class="sourceCode" id="cb434"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb434-1"><a href="voting.html#cb434-1" tabindex="-1"></a><span class="fu">plot</span>(florida<span class="sc">$</span>Perot96, florida<span class="sc">$</span>Buchanan00, </span>
<span id="cb434-2"><a href="voting.html#cb434-2" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">16</span>,</span>
<span id="cb434-3"><a href="voting.html#cb434-3" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Votes for Perot in 1996&quot;</span>, </span>
<span id="cb434-4"><a href="voting.html#cb434-4" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Votes for Buchanan in 2000&quot;</span>)</span>
<span id="cb434-5"><a href="voting.html#cb434-5" tabindex="-1"></a>    <span class="fu">abline</span>(lm.florida)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:basescatter2"></span>
<img src="09-week9_files/figure-html/basescatter2-1.png" alt="Relationship Between Buchanan and Perot Votes" width="80%" />
<p class="caption">
Figure 9.5: Relationship Between Buchanan and Perot Votes
</p>
</div>
<p>We can also customize the appearance of the line in a few ways. For example, <code>lty=2</code> will make the line dashed instead of solid. <code>lty</code> stands for line type and you can use a variety (see the help file for <code>plot</code> and search for <code>lty</code> to see the different options). <code>col="red"</code> will turn the line red.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="voting.html#cb435-1" tabindex="-1"></a><span class="fu">plot</span>(florida<span class="sc">$</span>Perot96, florida<span class="sc">$</span>Buchanan00, </span>
<span id="cb435-2"><a href="voting.html#cb435-2" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">16</span>,</span>
<span id="cb435-3"><a href="voting.html#cb435-3" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">&quot;Votes for Perot in 1996&quot;</span>, </span>
<span id="cb435-4"><a href="voting.html#cb435-4" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Votes for Buchanan in 2000&quot;</span>)</span>
<span id="cb435-5"><a href="voting.html#cb435-5" tabindex="-1"></a>    <span class="fu">abline</span>(lm.florida, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:basescatter3"></span>
<img src="09-week9_files/figure-html/basescatter3-1.png" alt="Relationship Between Buchanan and Perot Votes" width="80%" />
<p class="caption">
Figure 9.6: Relationship Between Buchanan and Perot Votes
</p>
</div>
<p>Now let’s learn how to plot the regression line in ggplot. In ggplot, the plot command can actually estimate the regression itself. In order to do so we will add to our plot the <code>geom_smooth()</code> function. In general <code>geom_smooth</code> adds fitted lines or curves to a plot. If we want a linear regression line, we can specify <code>geom_smooth(method="lm")</code>. The option <code>lm</code> stands for linear model.</p>
<p>Further, we will want to specify <code>se=FALSE</code>. By default <code>geom_smooth()</code> adds measures of uncertainty to our regression line, which we won’t cover in this book. Lastly, we will use additional options to change the type and color of the line, as we did before. The full code to generate our scatter plot with a linear regression line appears below:</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="voting.html#cb436-1" tabindex="-1"></a><span class="fu">ggplot</span>(florida, <span class="at">mapping=</span><span class="fu">aes</span>(<span class="at">x=</span>Perot96, <span class="at">y=</span>Buchanan00)) <span class="sc">+</span> </span>
<span id="cb436-2"><a href="voting.html#cb436-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb436-3"><a href="voting.html#cb436-3" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Votes for Perot in 1996&quot;</span>) <span class="sc">+</span> </span>
<span id="cb436-4"><a href="voting.html#cb436-4" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Votes for Buchanan in 2000&quot;</span>) <span class="sc">+</span> </span>
<span id="cb436-5"><a href="voting.html#cb436-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>, <span class="at">linetype=</span><span class="st">&quot;dashed&quot;</span>,<span class="at">color=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb436-6"><a href="voting.html#cb436-6" tabindex="-1"></a><span class="co">#&gt; `geom_smooth()` using formula = &#39;y ~ x&#39;</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:geomscatter"></span>
<img src="09-week9_files/figure-html/geomscatter-1.png" alt="Relationship Between Buchanan and Perot Votes" width="80%" />
<p class="caption">
Figure 9.7: Relationship Between Buchanan and Perot Votes
</p>
</div>
</div>
<div id="predicted-values-and-residuals" class="section level2 hasAnchor" number="9.4">
<h2><span class="header-section-number">9.4</span> Predicted Values and Residuals<a href="voting.html#predicted-values-and-residuals" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Now that we have estimated and plotted our linear regression line, let’s review how to form predicted values and residuals.</p>
<p>In general, the predicted value is given by:</p>
<p><span class="math display">\[
\hat{Y}_i = \hat{\beta}_0 + \hat{\beta}_1 \cdot X_i
\]</span></p>
<p>This gives us our best guess for a value of <span class="math inline">\(Y_i\)</span> given a value of <span class="math inline">\(X_i\)</span>, based on the linear regression estimates. This is the best fit line we plotted in the prior section. We can use this equation to form predicted values. For example, imagine I tell you a Alachua county in 1996 cast 8,072 votes for Ross Perot. Based on this number and the linear regression, what do you expect to be the number of Pat Buchanan votes cast?</p>
<p><span class="math display">\[
\hat{Buchanan00_i}= 1.346 + 0.036 \cdot 8072 \approx 292
\]</span></p>
<p>In other words, we expect Alachua county to cast 292 votes for Pat Buchanan. Now, this is just a prediction. We are using a single variable (Ross Perot votes) to predict the number of Buchanan votes. In reality, the number of Buchanan votes likely depends on a variety of factors. Therefore, our model will have error associated with, which we refer to as the residual.</p>
<p>The residual is given by the difference between the actual value and the predicted value. For example, Alachua county cast 263 votes for Buchanan. The residual is therefore given by:</p>
<p><span class="math display">\[
\hat{residual}_i = Y_i - \hat{Y}_i=263-292 = -29
\]</span></p>
<p>Now, we could do this manually for every single observation, but it will be much easier to do this automatically in R. This will allow us to construct the residual for every county in the data. We are particularly interested in the residual for Palm Beach county. This residual will tell us how many more votes were cast in Palm Beach for Buchanan relative to what we would have expected based on the county’s voting patterns for Perot.</p>
<p>To do so we will again estimate a linear regression with <code>Buchanan00</code> as the dependent variable and <code>Perot96</code> as the independent variable.</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="voting.html#cb437-1" tabindex="-1"></a>lm.florida <span class="ot">&lt;-</span> <span class="fu">lm</span>(Buchanan00 <span class="sc">~</span> Perot96, <span class="at">data=</span>florida)</span></code></pre></div>
<p><code>lm.florida</code> is known as a list object. It contains a lot of information from our linear regression. We can use the <code>names()</code> function to figure out what <code>lm.florida</code> contains:</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="voting.html#cb438-1" tabindex="-1"></a><span class="fu">names</span>(lm.florida)</span>
<span id="cb438-2"><a href="voting.html#cb438-2" tabindex="-1"></a><span class="co">#&gt;  [1] &quot;coefficients&quot;  &quot;residuals&quot;     &quot;effects&quot;      </span></span>
<span id="cb438-3"><a href="voting.html#cb438-3" tabindex="-1"></a><span class="co">#&gt;  [4] &quot;rank&quot;          &quot;fitted.values&quot; &quot;assign&quot;       </span></span>
<span id="cb438-4"><a href="voting.html#cb438-4" tabindex="-1"></a><span class="co">#&gt;  [7] &quot;qr&quot;            &quot;df.residual&quot;   &quot;xlevels&quot;      </span></span>
<span id="cb438-5"><a href="voting.html#cb438-5" tabindex="-1"></a><span class="co">#&gt; [10] &quot;call&quot;          &quot;terms&quot;         &quot;model&quot;</span></span></code></pre></div>
<p>So many of the information stored here we won’t use in this course. But there are two elements that will be useful for us. You can see one of the names is <code>fitted.values</code> and another is <code>residual</code>. Fitted values is another name for predicted values.</p>
<p>We can extract the information from <code>lm.florida</code> by using the dollar sign operator. For example, if we want to add a new variable to the dataset that is the fitted value for each observation, we type:</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="voting.html#cb439-1" tabindex="-1"></a>florida<span class="sc">$</span>predBuchanan00 <span class="ot">&lt;-</span> lm.florida<span class="sc">$</span>fitted.values</span></code></pre></div>
<p><code>predBuchanan00</code> is the name of the new variable and it is equal to the fitted values from the regression estimation. We can similarly extract the residual from our <code>lm.florida</code> object and add to the data frame <code>florida</code>.</p>
<div class="sourceCode" id="cb440"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb440-1"><a href="voting.html#cb440-1" tabindex="-1"></a>florida<span class="sc">$</span>residuals <span class="ot">&lt;-</span> lm.florida<span class="sc">$</span>residuals</span></code></pre></div>
<p>Now, let’s look at the data to try and understand our process so far.</p>
<pre><code>#&gt; # A tibble: 67 × 4
#&gt;    county    Buchanan00 predBuchanan00 residuals
#&gt;    &lt;chr&gt;          &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
#&gt;  1 Alachua          263          291.     -28.3 
#&gt;  2 Baker             73           25.3     47.7 
#&gt;  3 Bay              248          214.      34.0 
#&gt;  4 Bradford          65           30.8     34.2 
#&gt;  5 Brevard          570          908.    -338.  
#&gt;  6 Broward          788         1401.    -613.  
#&gt;  7 Calhoun           90           24.0     66.0 
#&gt;  8 Charlotte        182          281.     -98.9 
#&gt;  9 Citrus           270          262.       8.49
#&gt; 10 Clay             186          119.      66.8 
#&gt; # ℹ 57 more rows</code></pre>
<p>So for Alachua county the number of Buchanan votes in 2000 was 263. The predicted Buchanan votes was 291.251 (if you view your data frame you will be able to see more decimal places). Therefore the residual is -28.3. The reason this is slightly different than what we had above is because when we formed this manually we rounded the coefficients in the regression. When R does the computation, it is much more precise than we were, which explains why predicted values and residuals are slightly different than the manual computation.</p>
<p>Now let’s order the dataset by the magnitude of the residual. Observations with large residuals will be those in which our predictions are very different than our predicted value. To sort data based on the value of a variable, we can use the <code>arrange()</code> function.</p>
<p>For our purposes we want to sort based on the absolute value of the residual. Therefore, we will specify <code>arrange(abs(residuals))</code>. The <code>abs()</code> function takes the absolute value of a number. However, in addition, we want the largest residuals to be at the top. By default, <code>arrange</code> sorts the data from lowest to highest. To change this, we can ask for the data to be presented in descending order, by specifying <code>arrange(desc(abs(residuals)))</code>. The <code>desc()</code> function specifies to order the data in descending order (from largest to smallest).</p>
<p>Additionally, we can combine <code>arrange</code> with other functions using the pipe operator. In this example, we are really only interested in a few variables at the moment. So let’s first select those variables, and then display the data from largest residual (in absolute value) to lowest residual.</p>
<div class="sourceCode" id="cb442"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb442-1"><a href="voting.html#cb442-1" tabindex="-1"></a>florida <span class="sc">%&gt;%</span> </span>
<span id="cb442-2"><a href="voting.html#cb442-2" tabindex="-1"></a>  <span class="fu">select</span>(county,Buchanan00,predBuchanan00,residuals) <span class="sc">%&gt;%</span></span>
<span id="cb442-3"><a href="voting.html#cb442-3" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(residuals)))</span></code></pre></div>
<pre><code>#&gt; # A tibble: 67 × 4
#&gt;    county     Buchanan00 predBuchanan00 residuals
#&gt;    &lt;chr&gt;           &lt;dbl&gt;          &lt;dbl&gt;     &lt;dbl&gt;
#&gt;  1 PalmBeach        3407          1105.     2302.
#&gt;  2 Broward           788          1401.     -613.
#&gt;  3 Lee               305           662.     -357.
#&gt;  4 Brevard           570           908.     -338.
#&gt;  5 Miami-Dade        560           889.     -329.
#&gt;  6 Pinellas         1013          1330.     -317.
#&gt;  7 Sarasota          305           538.     -233.
#&gt;  8 Orange            446           655.     -209.
#&gt;  9 Escambia          502           310.      192.
#&gt; 10 St.Lucie          124           306.     -182.
#&gt; # ℹ 57 more rows</code></pre>
<p>So Palm Beach county cast 3407 votes for Buchanan. Based on the linear regression, we would have expected 1105 votes for Buchanan. Therefore, there were 2302 more votes than expected.</p>
<p>Now recall the George Bush won Florida by 537 votes. Now, if the excess votes in Palm Beach were driven by the design of the butterfly ballots, then we are seeing this excess voting for Buchanan because individuals were confused about the design and were accidentally selecting Buchanan instead of Gore.</p>
<p>If this is true, then Al Gore would have actually received approximately 2,000 more votes. This would have been enough to make him the winner in Florida, and given the closeness of the election, the winner overall. In other words, using some simple data analysis techniques, we’ve found convincing evidence that a poorly designed ballot in a single Florida county was enough to flip the 2000 presidential election!</p>
</div>
<div id="get-out-to-vote-experiments" class="section level2 hasAnchor" number="9.5">
<h2><span class="header-section-number">9.5</span> Get Out to Vote Experiments<a href="voting.html#get-out-to-vote-experiments" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Next, we are going to shift gears to another voting application. One notorious issue in politics is getting people to vote. In particular, it is extremely difficult to get voters to turn out to vote in primary elections, even though primary elections are incredibly important. They select the candidates who will run in the general election. Yet, year after year, voter turnout for these primary elections is pretty low. For example, in California, voter turnout in general elections between 2000-2012 was about 65.5 percent among registered voters. In contrast, voter turnout in primary elections during this period was around 40.8 percent.</p>
<p>One reason for lack of voting may be due to a lack of mobilization. Maybe some simple information and encouragement to voting in primaries will incentivize individuals to vote. In Hill and Kousser (2016)<span class="citation">,<a href="#fn14" class="footnote-ref" id="fnref14"><sup>14</sup></a></span> the authors test this idea by implementing a large-scale experiment in the 2014 congressional primary elections in California.</p>
<p>In their study, Hill and Kousser were particularly interested in targeting those individuals who vote in general elections, but not in primaries. These are perhaps the individuals for which a treatment will be most successful. They are engaged in politics on big occasions (general elections), but not engaged in other occasions (primary elections).</p>
<p>To be specific, Hill and Kousser sent three types of letters to individuals in advance of the 2014 primary election</p>
<ul>
<li>Letter 1: Basic information about the election</li>
<li>Letter 2: Basic information plus information about California top two primaries</li>
<li>Letter 3: Basic information plus information about turnout for the respondent’s party</li>
</ul>
<p>The letters were aimed at testing different reasons why people may or may not vote. Letter 1 tests whether basic information about when the election is occurring helps promote turnout. Letter 2 is aimed to providing information about one particularly confusing element of Congressional campaigns in California. In 2012, a law in California was passed that made it a “top-two” primary state. This means that any individual in California can vote for any candidate in a primary, regardless of party affiliation. The top two candidates with the most votes then continue to the general election in November. Under this system it is possible that the top two candidates come from the same party. Hill and Kousser wanted to test whether lack of understanding about the new system prevented some from voting.</p>
<p>The last letter also included information about voter turnout among the respondents party. The authors hypothesize that seeing low voter turnout among your party may be especially effective in incentivizing an individual to vote. In other words, individuals registered as Republican were provided the Republican voter turnout in the prior election, while individuals registered as Democrats were provided the voter turnout for Democrats in the prior election.</p>
<p>One impressive aspect of this experiment is its scale. In total, Hill and Kousser (2016) sent around 150,000 letters to Californians before the election. This will allow us to get very precise answers to how informational interventions impact voter turnout. Additionally, given voting records are public data, we also have a very large control group in this experiment: individuals who did not receive one of the three letters.</p>
</div>
<div id="regression-binary-variables" class="section level2 hasAnchor" number="9.6">
<h2><span class="header-section-number">9.6</span> Regression (Binary Variables)<a href="voting.html#regression-binary-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>To study the impacts of receiving a mailer on voter turnout, we are again going to turn to linear regression. For our purposes, we will study the impact of receiving any mailer. Therefore, conceptually, you should think of individuals who received any letter as the treatment group, and individuals who did not receive a letter as the control group. To estimate the impact of receiving a mailer we will estimate a linear regression of the following form:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 \cdot X_i + \varepsilon_i
\]</span></p>
<p>Where <span class="math inline">\(Y_i\)</span> is equal to 1 if the individual voted and zero otherwise, and <span class="math inline">\(X_i\)</span> is equal to one if the individual received a mailer and zero otherwise. This is a bit different than most of examples so far, because in this example both <span class="math inline">\(Y_i\)</span> and <span class="math inline">\(X_i\)</span> are binary, meaning they take on only two values.</p>
<p>What is the interpretation of <span class="math inline">\(\beta_1\)</span> in this example. Our general rule is: when <span class="math inline">\(X_i\)</span> increases by 1, this is associated with a <span class="math inline">\(\beta_1\)</span>-unit change in <span class="math inline">\(Y_i\)</span>. Because <span class="math inline">\(X_i=0\)</span> if in the control and 1 if in the treatment, a 1-unit increase in <span class="math inline">\(X_i\)</span> is going from control to treatment. In other words, moving an individual from the control to receiving a letter is associated with a <span class="math inline">\(\beta_1\)</span> unit change in <span class="math inline">\(Y_i\)</span>. But <span class="math inline">\(Y_i\)</span> is also binary. So imagine for a moment <span class="math inline">\(\beta_1=0.01\)</span>. What does a <span class="math inline">\(0.01\)</span> change in <span class="math inline">\(Y_i\)</span> imply? Well, this is a <span class="math inline">\(\beta_1 \cdot 100=0.01 \cdot 100 = 1\)</span> percentage point increase in <span class="math inline">\(Y_i\)</span>.</p>
<p>Another way to think through this interpretation is through predicted values. Imagine now <span class="math inline">\(\beta_0=0.5\)</span> and <span class="math inline">\(\beta_1=0.01\)</span>. Next, I ask what is the predicted value of <span class="math inline">\(Y_i\)</span> for an individual in the control (i.e. <span class="math inline">\(X_i=0\)</span>):</p>
<p><span class="math display">\[
\hat{Y}_i = \beta_0 + \beta_1 \cdot X_i = 0.5 + 0.01 \cdot 0 = 0.50
\]</span></p>
<p>In simpler terms, we expect 50 percent of individuals in the control to vote. Recall that when you take the average of a binary variable that takes on values of zero or one, this average is equal to the fraction of individuals with a 1. Therefore, in this case, a value of 0.5 indicates half the individuals have a value of <span class="math inline">\(Y_i=1\)</span>. Put even more simply, half of all individuals voted. Next, I ask what is the predicted value of <span class="math inline">\(Y_i\)</span> for an individual in the treatment:</p>
<p><span class="math display">\[
\hat{Y}_i = \beta_0 + \beta_1 \cdot X_i = 0.5 + 0.01 \cdot 1 = 0.51
\]</span>
Therefore, we expect 51 percent of individuals to vote in the treatment. Therefore, the impact of going to control to treatment is a 1 percentage point increase in the probability of voting. If you need a review on the difference between percent and percentage point, check out Chapter 1.8. Specifically, it would <strong>not</strong> be correct here to say that treatment increases voting rates by 1 percent. Now that we understand the interpretation of linear regression with binary variables, let’s go implement this regression in R to assess how receiving a mailer impacted voter turnout.</p>
<p>The data for this application comes from a csv file named <code>turnout.csv</code>. Let’s load this into R as a tibble.</p>
<div class="sourceCode" id="cb444"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb444-1"><a href="voting.html#cb444-1" tabindex="-1"></a>turnout <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;turnout.csv&quot;</span>)</span>
<span id="cb444-2"><a href="voting.html#cb444-2" tabindex="-1"></a><span class="co">#&gt; Rows: 3872268 Columns: 5</span></span>
<span id="cb444-3"><a href="voting.html#cb444-3" tabindex="-1"></a><span class="co">#&gt; ── Column specification ────────────────────────────────────</span></span>
<span id="cb444-4"><a href="voting.html#cb444-4" tabindex="-1"></a><span class="co">#&gt; Delimiter: &quot;,&quot;</span></span>
<span id="cb444-5"><a href="voting.html#cb444-5" tabindex="-1"></a><span class="co">#&gt; chr (2): Party, treatment.assign</span></span>
<span id="cb444-6"><a href="voting.html#cb444-6" tabindex="-1"></a><span class="co">#&gt; dbl (3): LocalityCode, yvar, mailer</span></span>
<span id="cb444-7"><a href="voting.html#cb444-7" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb444-8"><a href="voting.html#cb444-8" tabindex="-1"></a><span class="co">#&gt; ℹ Use `spec()` to retrieve the full column specification for this data.</span></span>
<span id="cb444-9"><a href="voting.html#cb444-9" tabindex="-1"></a><span class="co">#&gt; ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</span></span></code></pre></div>
<p>This is a very large dataset. The data includes information on over 3.8 million individuals in California. Let’s take a look at a small slice of the data:</p>
<pre><code>#&gt; # A tibble: 3,872,268 × 5
#&gt;    LocalityCode Party  yvar treatment.assign mailer
#&gt;           &lt;dbl&gt; &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;             &lt;dbl&gt;
#&gt;  1            1 REP       0 Control               0
#&gt;  2            1 NPP       0 Control               0
#&gt;  3            1 DEM       1 Control               0
#&gt;  4            1 REP       0 Control               0
#&gt;  5            1 DEM       0 Control               0
#&gt;  6            1 NPP       0 Control               0
#&gt;  7            1 DEM       0 Control               0
#&gt;  8            1 DEM       0 Control               0
#&gt;  9            1 REP       0 Control               0
#&gt; 10            1 NPP       0 Control               0
#&gt; # ℹ 3,872,258 more rows</code></pre>
<p>The first variable <code>LocalityCode</code> indicates the county the individual is voting in. <code>Party</code> is the registered party of the individual. <code>yvar</code> is our main dependent variable. This variable is equal to 1 if the individual voted in the 2014 primary election and zero if the individual did not vote. <code>treatment.assign</code> indicates whether this individual is in the control group (i.e. did not receive a letter) or one of the treatment arms. The last variable <code>mailer</code> is equal to 1 if the individual received any mailer, and zero if the individual is in the control group.</p>
<p>For our application, we want to test whether receiving a mailer impacts the probability an individual votes. Therefore, we will regress the variable <code>yvar</code> on the variable <code>mailer</code>. Just as before, we need to save our estimates as a new object.</p>
<div class="sourceCode" id="cb446"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb446-1"><a href="voting.html#cb446-1" tabindex="-1"></a>lm.turnout <span class="ot">&lt;-</span> <span class="fu">lm</span>(yvar <span class="sc">~</span> mailer, <span class="at">data=</span>turnout)</span></code></pre></div>
<p>Now let’s look at the results:</p>
<div class="sourceCode" id="cb447"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb447-1"><a href="voting.html#cb447-1" tabindex="-1"></a>lm.turnout</span>
<span id="cb447-2"><a href="voting.html#cb447-2" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb447-3"><a href="voting.html#cb447-3" tabindex="-1"></a><span class="co">#&gt; Call:</span></span>
<span id="cb447-4"><a href="voting.html#cb447-4" tabindex="-1"></a><span class="co">#&gt; lm(formula = yvar ~ mailer, data = turnout)</span></span>
<span id="cb447-5"><a href="voting.html#cb447-5" tabindex="-1"></a><span class="co">#&gt; </span></span>
<span id="cb447-6"><a href="voting.html#cb447-6" tabindex="-1"></a><span class="co">#&gt; Coefficients:</span></span>
<span id="cb447-7"><a href="voting.html#cb447-7" tabindex="-1"></a><span class="co">#&gt; (Intercept)       mailer  </span></span>
<span id="cb447-8"><a href="voting.html#cb447-8" tabindex="-1"></a><span class="co">#&gt;    0.093125     0.004899</span></span></code></pre></div>
<p>So let’s interpret this regression. To do so, let’s compute what the regression predicts regarding voting for an individual in the control:</p>
<p><span class="math display">\[
\hat{Y}_i = 0.093 + 0.005 \cdot 0 = 0.093
\]</span></p>
<p>In simple terms, 9.3 percent of individuals in the control group voted in the election. For individuals in the treatment, we get:</p>
<p><span class="math display">\[
\hat{Y}_i = 0.093 + 0.005 \cdot 1 = 0.093+ 0.005 = 0.098
\]</span></p>
<p>Therefore, in the treatment group, about 9.8 percent of individuals turned out to vote. Therefore, our treatment is expected to increase voting rates by 0.5 percentage points.</p>
</div>
<div id="conclusion-7" class="section level2 hasAnchor" number="9.7">
<h2><span class="header-section-number">9.7</span> Conclusion<a href="voting.html#conclusion-7" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this chapter, we have introduced two voting examples. In the first application, we showed that a poorly designed ballot may have changed the 2000 U.S. Presidential election. In the second, we showed that a massive campaign that sent mailers to over 150,000 Californians increased voter turnout in primary elections.
In both of these applications, we used regression to analyze the data. In our first application, regression gave us a way to form predictions. In particular, we needed to form a prediction for Palm Beach County regarding how many votes Pat Buchanan (the Reform Party Candidate) would receive. This was important because after the election, individuals claimed that the ballot was confusing, and led people to mistakenly vote for Pat Buchanan rather than Al Gore (check out Figure <a href="voting.html#fig:butterfly">9.1</a> to see if you agree).</p>
<p>However, we still needed a way in the data to see whether it appears that “too many” individuals voted for Pat Buchanan. To do this, we predicted county-level votes for Pat Buchanan using the number of votes cast for Ross Perot in 1996. This is likely a good predictor because Ross Perot and Pat Buchanan were both from the same party (the Reform Party).</p>
<p>Using the regression estimates, we predicted that Palm Beach county would cast 1105 votes for Buchanan. In actuality, Palm Beach cast 3407 votes for Buchanan. In other words, Palm Beach had over 2000 more votes for Buchanan than expected. This discrepancy is large enough to potentially swing the election. George Bush won Florida by only 537 votes. Had those 2000 votes for Buchanan been cast for Al Gore, then Al Gore would have won Florida and the election overall.</p>
<p>In the second application, we used regression to estimate a treatment effect: the effect of receiving a mailer on voter turnout. It is notoriously difficult to get individuals to vote in primary elections. In Hill and Kousser (2016), the authors sent an astounding 150,000 letters to Californians, providing them with different forms of information about the election. The scope of the project allowed the authors to detect even small changes in voting behavior. In the end, they found the mailer increased voting by about 0.5 percentage points. This may seem small, but if applied to the population of California, this implies thousands of additional voters.</p>
</div>
<div id="function-descriptions-3" class="section level2 unnumbered hasAnchor">
<h2><u>Function Descriptions</u><a href="voting.html#function-descriptions-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="rmdnote">
<p><strong><u>Functions Used</u></strong></p>
<ul>
<li><p><code>lm</code> – Estimates linear regression in R. General syntax is given by <code>lm.fit &lt;- lm(yvar ~ xvar, data=df)</code>. <code>lm.fit</code> is an object that is created and contains results of the linear regression.</p>
<ul>
<li><code>lm</code> stores many important results from linear regression, including <code>coefficients</code>, <code>fitted.values</code>, and <code>residuals</code>. To extract an element type <code>lm.fit$coefficients</code>.</li>
</ul></li>
<li><p><code>abline</code> – adds linear regression line to plots in Base R.</p></li>
<li><p><code>geom_smooth(method="lm",se=FALSE)</code> – adds linear regression line to plots in ggplot2.</p></li>
</ul>
</div>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="12">
<li id="fn12"><p>Jonathan N Wand et al., <span>“The Butterfly Did It: The Aberrant Vote for Buchanan in Palm Beach County, Florida,”</span> <em>American Political Science Review</em> 95, no. 4 (2001): 793–810.<a href="voting.html#fnref12" class="footnote-back">↩︎</a></p></li>
<li id="fn13"><p>Imai, <em>Quantitative Social Science</em>.<a href="voting.html#fnref13" class="footnote-back">↩︎</a></p></li>
<li id="fn14"><p>Seth J Hill and Thad Kousser, <span>“Turning Out Unlikely Voters? A Field Experiment in the Top-Two Primary,”</span> <em>Political Behavior</em> 38, no. 2 (2016): 413–32.<a href="voting.html#fnref14" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="automated-pollution-monitoring.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="unconditional-cash-transfers.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
